github.com:
    users:
        robertorodriguezarch:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: robertorodriguezarch
